draft-cardwell-ccwg-bbr.xml
This pull request corrects a misspelling of the word 'queue'.
=> fix: correct misspelling "que" to "queue"

draft-ietf-ccwg-bbr.md
According to this draft in relation with BBRAdaptLowerBoundsFromCongestion():
4.5.10.3. When not Probing for Bandwidth
When not explicitly accelerating to probe for bandwidth (Drain, ProbeRTT,
ProbeBW_DOWN, ProbeBW_CRUISE), BBR responds to loss by slowing down to some
extent.
this function should exclude the BBR states which are not aforementioned, that is to say Startup, ProbeBW_UP and ProbeBW_REFILL calling BBRIsProbingBW(). So, this latter should be implemented as follows:
BBRIsProbingBW():
return BBR.state == Startup or
BBR.state == ProbeBW_UP or
BBR.state == ProbeBW_REFILL
This patch directly inlines the code of BBRIsProbingBW().
=> BBRIsProbingBW() is not implemented

draft-ietf-ccwg-bbr.md
In the text description of the full pipe estimator, it counts three rounds. 
> if BBR counts several (three) non-application-limited rounds where attempts to significantly increase the
delivery rate actually result in little increase (less than 25 percent)
However, the pseudocode allows the full bw to be reset anytime during the round. Depending on the point in time in the round when this happens, this could reduce the time spent in the bandwdith plateau by up to one round. 
By moving the check for round_start earlier, the estimator is guaranteed to spend 3 full round trips in the plateau.
=> Ensure BBRCheckFullBWReached pseudo code counts three full rounds

draft-ietf-ccwg-bbr.md
This attempts to keep them when they're relevant and may have missed some.
Also there are some TODOs where I was confused what the text intended.  Hopefully @nealcardwell can let me know how to fix those.
Fixes #4
=> Remove some TCP and SACK references

draft-ietf-ccwg-bbr.md
Commit ea7c7c3f116ccec685c476 added some commentary about first_sent_time: "Additionally, TCP and other transport protocols that retransmit packets require".
But first_sent_time is not really about retransmits. Rather, it's about the first send time for a flight of outstanding data in the network, and is used for
computing the time elapsed to send the currently
outstanding flight of data.
This commit removes the commentary and moves
the definition of P.first_sent_time back to its original spot.
=> Revert recent prose about P.first_sent_time

draft-ietf-ccwg-bbr.md
Remove "(thus the name)" comments.
They no longer make sense after the longterm/shortterm rename.
Thanks for jbeshay@ pointing this out during a recent review!
=> Remove "(thus the name)" comments after longterm/shortterm rename

draft-ietf-ccwg-bbr.md
Recent commit ea7c7c3f116ccec685c476 made some nice improvements
by replacing verbose, TCP-specific text like "ACKed or SACKed"
with succinct and transport-agnostic terms like "acknowledged".
Let's add text to be very clear about what we  mean by those terms,
s ince they are key, and TCP implementors may be
confused about whether "acknowledged" includes SACKs.
=> define "acknowledged" and "delivered" in a transport-agnostic way

draft-ietf-ccwg-bbr.md
Fixes #36.
Remove accidental duplicate IsInflightTooHigh() function definition.
=> Remove duplicate IsInflightTooHigh() function definition

draft-ietf-ccwg-bbr.md
Define "inflight" and use it more precisely and consistently.
Rephrase text using the phrase or variable name "inflight" for values that are not exactly consistent with the definition of "inflight".
Part of a fix for #14.
=> define "inflight" and use it more precisely and consistently

draft-ietf-ccwg-bbr.md
- Use CamelCase for constant names
- Use snake_case for variable names
- All names have prefixes:
- C: connection state
- P: per-packet state
-  rs: per-ack rate sample
- BBR: bbr's internal state
=> Use consistent prefixes and casing for variable and constant names

draft-ietf-ccwg-bbr.md
Also merge the descriptions, since they were slightly different.
=> Remove second definition of C.delivered

draft-ietf-ccwg-bbr.md
This is an attempt to make the pseudocode for BBR and the delivery estimation work together a little bit better.
- Adds RS as a new BBR state variable.
- Adds C.min_rtt instead of MinRTT(tp) that was used by the delivery estimation psuedocode but not defined.
- Remove usage of SND.NXT and SND.UNA
- BBRUpdateOnAck now calls GenerateRateSample().
BBROnTransmit() and OnPacketSent() are still separate because the former is before a packet is transmitted and the latter is after.
Addresses #49
=> Improve consistency between core BBR and delivery rate estimation pseudocode

draft-ietf-ccwg-bbr.md
* Remove duplicate definitions for the output parameters
* Use consistent spelling for "acknowledgment"
Fixes https://github.com/ietf-wg-ccwg/draft-ietf-ccwg-bbr/issues/54
=> Remove duplicate definitions for the output parameters and fix "acknowledgment" spelling

draft-ietf-ccwg-bbr.md
C.write_seq and SND.UNA and SND.MSS are only used in one spot in psuedocode, which I attempted to generalize, but there is likely a better approach.
=> Remove C.write_seq because it's TCP-specific

draft-ietf-ccwg-bbr.md
The date should get inserted by the tooling upon submission, and explicitly specifying it seems to be overriding that.
=> Remove the date from the metadata

draft-ietf-ccwg-bbr.md
Refine the definition of C.SMSS to make it more precise.
Also try to fix its TCP-centric definition that uses the term "segment", and make it general to any transport protocol implementation, and clarify what implementations MUST and MAY do.
Also clarify what TCP and QUIC implementations SHOULD do, since there is extensive experience with BBR with both of those protocols.
Helps resolve Issue #62  "segment vs packet".
=> Refine definition of C.SMSS

draft-ietf-ccwg-bbr.md
Previously P.tx_in_flight was defined, and read in
BBRHandleLostPacket() pseudocode, but there was no pseudocode to set
P.tx_in_flight. This was an oversight.
This commit inserts a line to set P.tx_in_flight in OnPacketSent(),
matching the behavior in the Linux TCP BBR code.
Closes #77 ("set P.tx_in_flight").
=> set P.tx_in_flight in OnPacketSent()

draft-ietf-ccwg-bbr.md
Have the "per-packet state" section and "offload" section
cross-reference each other, and have both spots clarify
that it's recommended to track state per offload aggregate.
Make a key clarification about P.tx_in_flight reflecting the
inflight data after the transmission of P:
-P.tx_in_flight: C.inflight at the time of the packet transmission.
+P.tx_in_flight: C.inflight immediately after the transmission of packet P.
Fixes #66
=> clarify relationship between per-packet state and offload mechanisms

draft-ietf-ccwg-bbr.md
Clarify that all pseudocode functions have access to implicit (C) and
(BBR) parameters (e.g., via a Transmission Control Block or TCB in
TCP, or a "this" pointer in a C++ implementation of QUIC or other
user-space transports), and ACK-related functions also have access to
an implicit (RS) parameter.
Clarify the relationship of (RS) and (P) in handling for ACKs, which
can mark 0, 1, or many packets as acknowledged:
+ first call InitRateSample() once per ACK
+ then call UpdateRateSample() once per packet P acknowledged by the current ACK
+ finally call GenerateRateSample() after those steps
Fixes #58
=> clarify implicit C, BBR, RS parameters and relationship of RS and P in stretch ACKs

draft-ietf-ccwg-bbr.md
Clarify near the start of the "Terminology" section that this document uses units of bytes, sec, and bytes/sec.
Clarify that implementations may use other units, with appropriate conversions (since Linux TCP uses packets).
But note that it is RECOMMENDED to use bytes rather than packets, since packet sizes can vary.
Try to remove mentions of units in the main sections of the document. Where it's more clear to use units, make sure the text is consistent with the bytes, sec, and bytes/sec units.
To keep the doc more succinct and readable, and avoid churn, and avoid cognitive dissonance with respect to
implementations using other units (like Linux TCP), we still avoid putting units in the names of variables in this doc.
Fixes #27
=> clarify that BBR doc uses units of bytes, sec, and bytes/sec
